
apiVersion: v1
kind: Template

labels:
  application: mlflow-s3-secret

metadata:
  name: mlflow-s3-secret
  annotations:
    description: "Open Data Hub - MLFlow S3 Secret "
    tags: "mlflow,aicoe,datahub,mljob,storage,secret"

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_KEY}
  data:
  stringData:
    MLFLOW_S3_ENDPOINT_URL: "${MLFLOW_S3_ENDPOINT_URL}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    MLFLOW_EXTRA_OPS: "${MLFLOW_EXTRA_OPS}"
    SECRET_KEY: "${SECRET_KEY}"


parameters:
- name: AWS_ACCESS_KEY_ID
  required: true
- name: AWS_SECRET_ACCESS_KEY
  required: true
- name: MLFLOW_S3_ENDPOINT_URL
- name: MLFLOW_EXTRA_OPS
  required: true
- name: SECRET_KEY
  required: true
