apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  creationTimestamp: null
  name: mlflow-tracking-operator.v0.1.0
  namespace: mlflow-olm
  annotations:
    categories: "MLFlow - Model Lifecycle Management"
    certified: "false"
    containerImage: quay.io/zmhassan/mlflow-tracking-operator
    capabilities: Seamless Upgrades
    support: Mlflow
    description: Provides hyperparameter tooling and model lifecycle management for machine learning jobs
    alm-examples: |-
      apiVersion: ai.mlflow.org/v1alpha1
      kind: TrackingServer
      metadata:
        name: zak-tracking-server
      spec:
        # Add fields here
        size: 2
        Image: "quay.io/zmhassan/mlflow:0.8.2"

spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: TrackingServer
      name: trackingservers.ai.mlflow.org
      version: v1alpha1
      description: MLFlow Tracking Server for experiment tracking of machine learning jobs
      displayName: OpenDatahub - Mlflow Tracking Operator

  description: MLFlow Tracking Server for experiment tracking of machine learning jobs
  displayName: OpenDatahub - Mlflow Tracking Operator
  keywords: ['mlflow', 'hyperparameter-tuning', 'machine-learning']
  maintainers:
    - name: Zak Hassan
      email: zak.hassan@redhat.com
  links:
    - name: MLFlow Source Code
      url: https://github.com/zmhassan/mlflow-tracking-operator
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: true
  install:
    spec:
      deployments:
      - name: mlflow-tracking-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: mlflow-tracking-operator
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                name: mlflow-tracking-operator
            spec:
              containers:
              - command:
                - mlflow-tracking-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: mlflow-tracking-operator
                image: quay.io/zmhassan/mlflow-tracking-operator
                imagePullPolicy: Always
                name: mlflow-tracking-operator
                resources: {}
              serviceAccountName: mlflow-tracking-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - ai.mlflow.org
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: mlflow-tracking-operator
    strategy: deployment
  maturity: alpha
  provider:
    name: Mlflow
  labels:
    name: mlflow-tracking-operator
  selector:
    matchLabels:
      name: mlflow-tracking-operator
  version: 0.1.0
